export const productos = [
    {
        codigo: 1,
        nombre: "Old Skool", 
        cantidad: 20,
        precio: 89000,
        imagen: "../media/zapatillas/zap1.webp",
        imagen2: "../media/zapatillas/zap1-2-.jpg",
        descripcion: "Vans Old Skool",
        marca: "Vans",
        color: "Negro/Blanco"
    },
    {
        codigo: 2,
        nombre: "Originals Forum Low CL",
        cantidad: 20,
        precio: 162000,
        imagen: "../media/zapatillas/zap2.jpg",
        imagen2: "../media/zapatillas/zap2-2.jpg",
        descripcion: "Adidas Originals Forum Low CL",
        marca: "Adidas",
        color: "Crema/Rojo"
    },
    {
        codigo: 3,
        nombre: "Air Jordan 1 High Obsidian",
        cantidad: 20,
        precio: 269000,
        imagen: "../media/zapatillas/zap3.png",
        imagen2: "../media/zapatillas/zap3-2.png",
        descripcion: "Nike Air Jordan 1 High Obsidian",
        marca: "Nike",
        color: "Azul/Blanco/Celeste"
    },
    {
        codigo: 4,
        nombre: "Court Graffik",
        cantidad: 20,
        precio: 149000,
        imagen: "../media/zapatillas/zap4.webp",
        imagen2: "../media/zapatillas/zap4-2.webp",
        descripcion: "DC Court Graffik",
        marca: "DC",
        color: "Negro"
    },
    {
        codigo: 5,
        nombre: "Star Player 76 Ox",
        cantidad: 20,
        precio: 119000,
        imagen: "../media/zapatillas/zap5.jpg",
        imagen2: "../media/zapatillas/zap5-2.jpg",
        descripcion: "Converse Star Player 76 Ox",
        marca: "Converse",
        color: "Marron"
    },
    {
        codigo: 6,
        nombre: "Knu Skool",
        cantidad: 20,
        precio: 162750,
        imagen: "../media/zapatillas/zap6.jpg",
        imagen2: "../media/zapatillas/zap6-2.jpg",
        descripcion: "Vans Knu Skool",
        marca: "Vans",
        color: "Negro"
    },
    {
        codigo: 7,
        nombre: "Rock",
        cantidad: 20,
        precio: 119000,
        imagen: "../media/zapatillas/zap7.jpg",
        imagen2: "../media/zapatillas/zap7-2.jpg",
        descripcion: "47 Street Rock",
        marca: "47Street",
        color: "Negro"
    },
    {
        codigo: 8,
        nombre: "Forum Mid",
        cantidad: 20,
        precio: 142599,
        imagen: "../media/zapatillas/zap8.webp",
        imagen2: "../media/zapatillas/zap8-2.webp",
        descripcion: "Adidas Forum Mid",
        marca: "Adidas",
        color: "Gris"
    },
    {
        codigo: 9,
        nombre: "Chuck Taylor All Star Lugged 2.0 Striped Knit",
        cantidad: 20,
        precio: 249000,
        imagen: "../media/zapatillas/zap9.jpg",
        imagen2: "../media/zapatillas/zap9-2.jpg",
        descripcion: "Converse Chuck Taylor All Star Lugged 2.0 Striped Knit",
        marca: "Converse",
        color: "Celeste"
    },
    {
        codigo: 10,
        nombre: "Sk8 H Bota",
        cantidad: 20,
        precio: 185000,
        imagen: "../media/zapatillas/zap10.jpg",
        imagen2: "../media/zapatillas/zap10-2.jpg",
        descripcion: "Vans Sk8 H Bota",
        marca: "Vans",
        color: "Navy"
    },
    {
        codigo: 11,
        nombre: "Suede XL",
        cantidad: 20,
        precio: 179000,
        imagen: "../media/zapatillas/zap11.jpg",
        imagen2: "../media/zapatillas/zap11-2.jpg",
        descripcion: "Puma Suede XL",
        marca: "Puma",
        color: "Negro"
    },
    {
        codigo: 12,
        nombre: "Originals Forum Low CL",
        cantidad: 20,
        precio: 169000,
        imagen: "../media/zapatillas/zap12.jpg",
        imagen2: "../media/zapatillas/zap12-2.jpg",
        descripcion: "Adidas Originals Forum Low CL",
        marca: "Adidas",
        color: "Blanco"
    },
    {
        codigo: 13,
        nombre: "Royal Bb4590",
        cantidad: 20,
        precio: 79999,
        imagen: "../media/zapatillas/zap13.webp",
        imagen2: "../media/zapatillas/zap13-2.webp",
        descripcion: "Reebok Royal Bb4590",
        marca: "Reebok",
        color: "Crema"
    },
    {
        codigo: 14,
        nombre: "Star Player 76",
        cantidad: 20,
        precio: 119000,
        imagen: "../media/zapatillas/zap14.jpg",
        imagen2: "../media/zapatillas/zap14-2.jpg",
        descripcion: "Converse Star Player 76",
        marca: "Converse",
        color: "Negro"
    },
    {
        codigo: 15,
        nombre: "Air Max Excee",
        cantidad: 20,
        precio: 135000,
        imagen: "../media/zapatillas/zap15.jpg",
        imagen2: "../media/zapatillas/zap15-2.jpg",
        descripcion: "Nike Air Max Excee",
        marca: "Nike",
        color: "Negro"
    },
    {
        codigo: 16,
        nombre: "RS-X Triple ADP",
        cantidad: 20,
        precio: 142000,
        imagen: "../media/zapatillas/zap16.png",
        imagen2: "../media/zapatillas/zap16-2.png",
        descripcion: "Puma RS-X Triple ADP",
        marca: "Puma",
        color: "Negro"
    },
    {
        codigo: 17,
        nombre: "Mod Old Skool Cuadros",
        cantidad: 20,
        precio: 124500,
        imagen: "../media/zapatillas/zap17.jpg",
        imagen2: "../media/zapatillas/zap17-2.webp",
        descripcion: "Vans Mod Old Skool Cuadros",
        marca: "Vans",
        color: "Blanco"
    },
    {
        codigo: 18,
        nombre: "Weapon",
        cantidad: 20,
        precio: 158000,
        imagen: "../media/zapatillas/zap18.jpg",
        imagen2: "../media/zapatillas/zap18-2.jpg",
        descripcion: "Converse Weapon",
        marca: "Converse",
        color: "Negro"
    },
    {
        codigo: 19,
        nombre: "Comanche",
        cantidad: 20,
        precio: 189000,
        imagen: "../media/zapatillas/zap19.webp",
        imagen2: "../media/zapatillas/zap19-2.jpg",
        descripcion: "Dvs Comanche",
        marca: "Dvs",
        color: "Gris/Negro/Oro"
    },
    {
        codigo: 20,
        nombre: "Knu Skool",
        cantidad: 20,
        precio: 213000,
        imagen: "../media/zapatillas/zap20.jpg",
        imagen2: "../media/zapatillas/zap20-2.jpg",
        descripcion: "Vans Knu Skool",
        marca: "Vans",
        color: "Navy"
    },
    {
        codigo: 21,
        nombre: "Court Graffik",
        cantidad: 20,
        precio: 159000,
        imagen: "../media/zapatillas/zap21.jpg",
        imagen2: "../media/zapatillas/zap21-2.png",
        descripcion: "DC Court Graffik",
        marca: "DC",
        color: "Blanco"
    },
    {
        codigo: 22,
        nombre: "Suede XL",
        cantidad: 20,
        precio: 179999,
        imagen: "../media/zapatillas/zap22.jpg",
        imagen2: "../media/zapatillas/zap22-2-.jpg",
        descripcion: "Puma Suede XL",
        marca: "Puma",
        color: "Crema"
    },
    {
        codigo: 23,
        nombre: "Court Vision Alta",
        cantidad: 20,
        precio: 164000,
        imagen: "../media/zapatillas/zap23.jpg",
        imagen2: "../media/zapatillas/zap23-2.jpg",
        descripcion: "Nike Court Vision Alta",
        marca: "Nike",
        color: "Blanco"
    },
    {
        codigo: 24,
        nombre: "Chuck 70 At Cx Hi",
        cantidad: 20,
        precio: 168000,
        imagen: "../media/zapatillas/zap24.webp",
        imagen2: "../media/zapatillas/zap24-2.webp",
        descripcion: "Converse Chuck 70 At Cx Hi",
        marca: "Converse",
        color: "Negro"
    },
    {
        codigo: 25,
        nombre: "Inverse Premium Wns",
        cantidad: 20,
        precio: 210000,
        imagen: "../media/zapatillas/zap25.png",
        imagen2: "../media/zapatillas/zap25-2.png",
        descripcion: "Puma Inverse Premium Wns",
        marca: "Puma",
        color: "Gris"
    },
    {
        codigo: 26,
        nombre: "Comanche",
        cantidad: 20,
        precio: 189000,
        imagen: "../media/zapatillas/zap26.webp",
        imagen2: "../media/zapatillas/zap26-2.webp",
        descripcion: "Dvs Comanche",
        marca: "Dvs",
        color: "Blanco/Negro"
    },
    {
        codigo: 27,
        nombre: "Reed Chunky",
        cantidad: 20,
        precio: 95500,
        imagen: "../media/zapatillas/zap27.jpg",
        imagen2: "../media/zapatillas/zap27-2.jpg",
        descripcion: "Rusty Reed Chunky",
        marca: "Rusty",
        color: "Negro"
    },
    {
        codigo: 28,
        nombre: "Chuck 70 Plus",
        cantidad: 20,
        precio: 129000,
        imagen: "../media/zapatillas/zap28.webp",
        imagen2: "../media/zapatillas/zap28-2.webp",
        descripcion: "Converse Chuck 70 Plus",
        marca: "Converse",
        color: "Blanco"
    },
    {
        codigo: 29,
        nombre: "Sk8 Bota",
        cantidad: 20,
        precio: 146000,
        imagen: "../media/zapatillas/zap29.webp",
        imagen2: "../media/zapatillas/zap29-2.jpg",
        descripcion: "Vans Modelo Sk8 Bota",
        marca: "Vans",
        color: "Negro"
    },
    {
        codigo: 30,
        nombre: "Workout Pro Mid",
        cantidad: 20,
        precio: 98000,
        imagen: "../media/zapatillas/zap30.webp",
        imagen2: "../media/zapatillas/zap30-2.webp",
        descripcion: "Reebok Workout Pro Mid",
        marca: "Reebok",
        color: "Crema"
    },
    {
        codigo: 31,
        nombre: "RS-X Landscapes Andes",
        cantidad: 20,
        precio: 107000,
        imagen: "../media/zapatillas/zap31.png",
        imagen2: "../media/zapatillas/zap31-2.png",
        descripcion: "Puma RS-X Landscapes Andes",
        marca: "Puma",
        color: "Crema"
    },
    {
        codigo: 32,
        nombre: "Forum Low 84",
        cantidad: 20,
        precio: 161900,
        imagen: "../media/zapatillas/zap32.webp",
        imagen2: "../media/zapatillas/zap32-2.webp",
        descripcion: "Adidas Forum Low 84",
        marca: "Adidas",
        color: "Crema/Azul"
    },
    {
        codigo: 33,
        nombre: "Rock",
        cantidad: 20,
        precio: 119000,
        imagen: "../media/zapatillas/zap33.png",
        imagen2: "../media/zapatillas/zap33-2.jpg",
        descripcion: "47 Street Rock",
        marca: "47Street",
        color: "Crema"
    },
    {
        codigo: 34,
        nombre: "Chuck Taylor All Star Move Hi A10439c",
        cantidad: 20,
        precio: 129000,
        imagen: "../media/zapatillas/zap34.webp",
        imagen2: "../media/zapatillas/zap34-2.webp",
        descripcion: "Converse Chuck Taylor All Star Move Hi A10439c",
        marca: "Converse",
        color: "Azul"
    },
    {
        codigo: 35,
        nombre: "Versatil Rs (Wlk)",
        cantidad: 20,
        precio: 179000,
        imagen: "../media/zapatillas/zap35.webp",
        imagen2: "../media/zapatillas/zap35-2.webp",
        descripcion: "DC Versatil Rs (Wlk)",
        marca: "DC",
        color: "Blanco"
    },
    {
        codigo: 36,
        nombre: "Carina Street Mid",
        cantidad: 20,
        precio: 139000,
        imagen: "../media/zapatillas/zap36.jpg",
        imagen2: "../media/zapatillas/zap36-2.jpg",
        descripcion: "Puma Carina Street Mid",
        marca: "Puma",
        color: "Negro"
    },
    {
        codigo: 37,
        nombre: "Air Force 1 '07",
        cantidad: 20,
        precio: 219000,
        imagen: "../media/zapatillas/zap37.jpg",
        imagen2: "../media/zapatillas/zap37-2.jpg",
        descripcion: "Nike Air Force 1 '07",
        marca: "Nike",
        color: "Negro/Blanco"
    },
    {
        codigo: 38,
        nombre: "Courtblock Bold",
        cantidad: 20,
        precio: 89900,
        imagen: "../media/zapatillas/zap38.png",
        imagen2: "../media/zapatillas/zap38-2.png",
        descripcion: "Adidas Courtblock Bold",
        marca: "Adidas",
        color: "Blanco"
    },
    {
        codigo: 39,
        nombre: "Lifestyle Unisex Chuck 70 Hi",
        cantidad: 20,
        precio: 118000,
        imagen: "../media/zapatillas/zap39.webp",
        imagen2: "../media/zapatillas/zap39-2.webp",
        descripcion: "Converse Lifestyle Unisex Chuck 70 Hi",
        marca: "Converse",
        color: "Negro"
    },
    {
        codigo: 40,
        nombre: "Air Max Pulse",
        cantidad: 20,
        precio: 200000,
        imagen: "../media/zapatillas/zap40.jpg",
        imagen2: "../media/zapatillas/zap40-2.jpg",
        descripcion: "Nike Air Max Pulse",
        marca: "Nike",
        color: "Gris"
    },
    {
        codigo: 41,
        nombre: "Air Jordan 1 Retro High OG 'Shadow 2.0'",
        cantidad: 20,
        precio: 224000,
        imagen: "../media/zapatillas/zap41.jpg",
        imagen2: "../media/zapatillas/zap41-2.png",
        descripcion: "Nike Air Jordan 1 Retro High OG 'Shadow 2.0'",
        marca: "Nike",
        color: "Negro/Gris"
    },
    {
        codigo: 42,
        nombre: "Suede XL",
        cantidad: 20,
        precio: 179000,
        imagen: "../media/zapatillas/zap42.png",
        imagen2: "../media/zapatillas/zap42-2.png",
        descripcion: "Puma Suede XL",
        marca: "Puma",
        color: "Azul/Rojo"
    },
    {
        codigo: 43,
        nombre: "Air Force 1 Wild",
        cantidad: 20,
        precio: 279000,
        imagen: "../media/zapatillas/zap43.jpg",
        imagen2: "../media/zapatillas/zap43-2.jfif",
        descripcion: "Nike Air Force 1 Wild",
        marca: "Nike",
        color: "Crema"
    },
    {
        codigo: 44,
        nombre: "Pure",
        cantidad: 20,
        precio: 132000,
        imagen: "../media/zapatillas/zap44.jpg",
        imagen2: "../media/zapatillas/zap44-2.jpg",
        descripcion: "DC Pure",
        marca: "DC",
        color: "Negro"
    },
    {
        codigo: 45,
        nombre: "Air Force 1 Shadow",
        cantidad: 20,
        precio: 200000,
        imagen: "../media/zapatillas/zap45.jpg",
        imagen2: "../media/zapatillas/zap45-2.jpg",
        descripcion: "Nike Air Force 1 Shadow",
        marca: "Nike",
        color: "Naranja/Blanco"
    },
    {
        codigo: 46,
        nombre: "Air Monarch IV Cross Trainer",
        cantidad: 20,
        precio: 212000,
        imagen: "../media/zapatillas/zap46.jpg",
        imagen2: "../media/zapatillas/zap46-2.jpg",
        descripcion: "Nike Air Monarch IV Cross Trainer",
        marca: "Nike",
        color: "Negro"
    },
    {
        codigo: 47,
        nombre: "Rock",
        cantidad: 20,
        precio: 119000,
        imagen: "../media/zapatillas/zap47.png",
        imagen2: "../media/zapatillas/zap47-2.png",
        descripcion: "47 Street Rock",
        marca: "47Street",
        color: "Blanco"
    },
    {
        codigo: 48,
        nombre: "Chuck Taylor",
        cantidad: 20,
        precio: 99900,
        imagen: "../media/zapatillas/zap48.jpg",
        imagen2: "../media/zapatillas/zap48-2.jpg",
        descripcion: "Converse Chuck Taylor con plataforma",
        marca: "Converse",
        color: "Celeste"
    },
    {
        codigo: 49,
        nombre: "Comanche",
        cantidad: 20,
        precio: 189000,
        imagen: "../media/zapatillas/zap49.webp",
        imagen2: "../media/zapatillas/zap49-2.webp",
        descripcion: "Dvs Comanche",
        marca: "Dvs",
        color: "Blanco/Negro"
    },
    {
        codigo: 50,
        nombre: "Handball Spezial",
        cantidad: 20,
        precio: 189000,
        imagen: "../media/zapatillas/zap50.jfif",
        imagen2: "../media/zapatillas/zap50-2.jfif",
        descripcion: "Adidas Handball Spezial",
        marca: "Adidas",
        color: "Azul"
    },
    {
        codigo: 51,
        nombre: "Samba OG",
        cantidad: 20,
        precio: 189999,
        imagen: "../media/zapatillas/zap51.webp",
        imagen2: "../media/zapatillas/zap51-2.webp",
        descripcion: "Adidas Samba OG",
        marca: "Adidas",
        color: "Blanco/Negro/Gris"
    }
]